schema:
  - https://api.github.com/graphql:
      headers:
        Authorization: Bearer ${GITHUB_GQL_PERSONAL_TOKEN}
  - https://api.opencollective.com/graphql/v2:
      headers:
        Personal-Token: ${OPENCOLLECTIVE_GQL_PERSONAL_TOKEN}
documents: '**/*.graphql'
